FROM node:20

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY prisma ./prisma/
COPY .env ./

RUN npm install -g pnpm
RUN pnpm install
RUN pnpx prisma generate

COPY . .

EXPOSE 3000

# Générez le code Prisma
# RUN pnpm prisma generate

# Exécutez les migrations Prisma (ajustez selon votre configuration)
# RUN pnpm prisma migrate dev
CMD ["pnpm", "run", "docker"]
