import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { ModeToggle } from '@/components/modeToggle'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import { signIn, signOut } from 'next-auth/react'
import { SignInButtons, SignOutButtons } from '@/components/nextAuthButtons'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="fr">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModeToggle />
          <header>
            <nav className='flex flex-row justify-around'>
              {session ?
                <>
                  <SignOutButtons />
                  <Link href='/mangas'><Button variant='secondary'>Mangas</Button></Link>
                </>
                :
                <>
                  <SignInButtons />
                  <Link href='/'><Button variant='secondary'>Home</Button></Link>
                </>
              }
            </nav>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
