import { ModeToggle } from "@/components/modeToggle";
import { SignInButtons, SignOutButtons } from "@/components/nextAuthButtons";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import Link from "next/link";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="fr">
      <body className={inter.className + 'flex flex-col justify-between items-end min-h-[100vh]'}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModeToggle />
          <header>
            <nav className="flex flex-row justify-around">
              {session ? (
                <>
                  <SignOutButtons />
                  <Link href="/mangas">
                    <Button variant="secondary">Mangas</Button>
                  </Link>
                </>
              ) : (
                <>
                  <SignInButtons />
                  <Link href="/">
                    <Button variant="secondary">Home</Button>
                  </Link>
                </>
              )}
            </nav>
          </header>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
